
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiladores.compiladorespractica.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUMERO = 51;
  public static final int PAR_DER = 29;
  public static final int COLOR_TEXTO_BLOQUE = 44;
  public static final int POR = 26;
  public static final int LETRA_SIZE_MIENTRAS = 43;
  public static final int SI = 6;
  public static final int MOSTRAR = 12;
  public static final int FIGURA_BLOQUE = 46;
  public static final int DIFERENTE = 16;
  public static final int LETRA_MIENTRAS = 42;
  public static final int PORCENTAJE = 32;
  public static final int ENTONCES = 7;
  public static final int SEPARADOR = 2;
  public static final int FIN = 4;
  public static final int NOT = 23;
  public static final int AND = 21;
  public static final int IGUAL = 14;
  public static final int FINMIENTRAS = 11;
  public static final int OR = 22;
  public static final int MIENTRAS = 9;
  public static final int LETRA_SIZE_BLOQUE = 48;
  public static final int DIV = 27;
  public static final int ID = 52;
  public static final int IGUAL_IGUAL = 15;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COLOR_BLOQUE = 45;
  public static final int COMA = 31;
  public static final int CADENA = 50;
  public static final int MENOS = 25;
  public static final int COLOR_MIENTRAS = 40;
  public static final int MENOR = 18;
  public static final int COLOR_TEXTO_MIENTRAS = 39;
  public static final int PAR_IZQ = 28;
  public static final int ERROR_LEXICO = 53;
  public static final int LETRA_BLOQUE = 47;
  public static final int MAYOR = 17;
  public static final int BARRA = 30;
  public static final int FIGURA_MIENTRAS = 41;
  public static final int DEFAULT = 33;
  public static final int MAYOR_IGUAL = 19;
  public static final int LEER = 13;
  public static final int HACER = 10;
  public static final int LETRA_SI = 37;
  public static final int COLOR_SI = 35;
  public static final int HEXCOLOR = 49;
  public static final int INICIO = 3;
  public static final int MENOR_IGUAL = 20;
  public static final int FINSI = 8;
  public static final int COLOR_TEXTO_SI = 34;
  public static final int FIGURA_SI = 36;
  public static final int VAR = 5;
  public static final int LETRA_SIZE_SI = 38;
  public static final int MAS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEPARADOR",
  "INICIO",
  "FIN",
  "VAR",
  "SI",
  "ENTONCES",
  "FINSI",
  "MIENTRAS",
  "HACER",
  "FINMIENTRAS",
  "MOSTRAR",
  "LEER",
  "IGUAL",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "PAR_IZQ",
  "PAR_DER",
  "BARRA",
  "COMA",
  "PORCENTAJE",
  "DEFAULT",
  "COLOR_TEXTO_SI",
  "COLOR_SI",
  "FIGURA_SI",
  "LETRA_SI",
  "LETRA_SIZE_SI",
  "COLOR_TEXTO_MIENTRAS",
  "COLOR_MIENTRAS",
  "FIGURA_MIENTRAS",
  "LETRA_MIENTRAS",
  "LETRA_SIZE_MIENTRAS",
  "COLOR_TEXTO_BLOQUE",
  "COLOR_BLOQUE",
  "FIGURA_BLOQUE",
  "LETRA_BLOQUE",
  "LETRA_SIZE_BLOQUE",
  "HEXCOLOR",
  "CADENA",
  "NUMERO",
  "ID",
  "ERROR_LEXICO"
  };
}

